server:
  port: 8081
  servlet:
    context-path: /micro-consumer

eureka:
  client:
    service-url:
     defaultZone: http://root:asd@localhost:8084/eureka-server/eureka,http://root:asd@localhost:8087/eureka-server/eureka,
  instance:
    ip-address: true
spring:
  application:
    name: movie
  security:
    user:
      name: root
      password: asd
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
    password: asd1345439
  cache:
    type: redis
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","hystrix.stream"]






